
#comments are allowed
    #even with spacing

-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 40 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 13 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 3 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 3 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 12 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 3 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 3 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 3 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 9 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 12 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 3 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 12 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 8 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 8 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 2 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 7 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 8 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 8 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 8 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 8 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 8 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 3 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 16 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 1 hostname
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
-n 4 sh -c 'LD_PRELOAD=$HOME/projects/flux/flux-core/src/lib/libpmi/.libs/libpmi.so ../flux-core/src/test/mpi_hello'
-n 1 hostname
